kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data #database-persistent-volume-claim
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
