apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
        - name: data #postgres-storage
          persistentVolumeClaim:
            claimName: data #database-persistent-volume-claim
      containers:
        - name: postgres
          image: postgres:9.4.22
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data #postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: data #postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
